# -*- coding: utf-8 -*-
"""NBA Player Stats

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o3-4cIsPTZK301iX_3QSrNd2Fz5-sZS8
"""

import pandas as pd
import numpy as np

url = '/content/NBA_Player_Stats.csv';
data = pd.read_csv(url)

display(data)

data.head(3)

data.tail(5)

data.info()

data.describe()

data.groupby(['Player']).size()

data.Tm

posisi = data.Pos == 'SG'
tim = data.Tm == 'SAC'

data[(posisi) & (tim)]